---
- name: store stop shell file to remote server
  copy:
    src: "/home/ubuntu/ansibles/roles/deploy/files/{{ service.name }}/stop.sh"
    dest: "/home/ubuntu/{{ service.name }}"
- name: server stop
  shell: "sh '/home/ubuntu/{{ service.name }}/stop.sh'"
- name: store jar file to remote server
  copy:
    src: "/var/lib/jenkins/workspace/{{ service.name }}{{ service.subName }}/build/libs/{{ service.jar }}.jar"
    dest: "/home/ubuntu/{{ service.name }}"
- name: server startup
  shell: "nohup java -jar /home/ubuntu/{{ service.name }}/{{ service.jar }}.jar &"
