---
- name: stop nginx
  tags: stop
  block:
  - name: stop nginx
    shell: "{{ nginx_directory }}/sbin/nginx -s stop"
    ignore_errors: yes

- name: store build file to remote server
  copy:
    src: /var/lib/jenkins/workspace/front/build
    dest: /var/www/front-app

- name: start nginx
  tags: start
  block:
  - name: start nginx
    shell: "{{ nginx_directory }}/sbin/nginx"
