---
- name: stop nginx
  tags: stop
  block:
  - name: stop nginx
    shell: "sudo /etc/init.d/nginx stop"
    ignore_errors: yes

- name: store build file to remote server
  command: sudo cp -r /var/lib/jenkins/workspace/front /var/www/front-app/workspace/front

- name: start nginx
  tags: start
  block:
  - name: start nginx
    shell: "sudo /etc/init.d/nginx start"
